Homework 2
alinnegrea/scoala-informala-homeworks pull request #1
Opened 2017-07-30 17:10 UTC by alinnegrea

Homework-2 submission on GitHub

2017-08-06 14:00 UTC, andrei-hegedus commented on java-grupa8/homework-2/src/main/java/ro/siit/java8/SalesRepresentatives.java
> +public class SalesRepresentatives {
Clasele sunt scrise la singular: SalesRepresentative.

2017-08-06 14:00 UTC, andrei-hegedus commented on java-grupa8/homework-2/src/main/java/ro/siit/java8/main.java
> +public class Main {
Java class files must have the same name as the class: Main.java and not main.java.

2017-08-06 14:00 UTC, andrei-hegedus commented on java-grupa8/homework-2/src/main/java/ro/siit/java8/main.java
> +        for (int i = 0; i < 10; i++) {
This is not Bubble Sort. You implemented a brute force matching of all numbers with all numbers.
Bubble sort has extra conditions, please look over it again: https://en.wikipedia.org/wiki/Bubble_sort

2017-08-06 14:02 UTC, andrei-hegedus requested changes
See my comments.

2017-08-08 09:19 UTC, alinnegrea commented on java-grupa8/homework-2/src/main/java/ro/siit/java8/SalesRepresentatives.java
> +public class SalesRepresentatives {
Done

2017-08-08 09:19 UTC, alinnegrea commented on java-grupa8/homework-2/src/main/java/ro/siit/java8/main.java
> +public class Main {
Done

2017-08-08 09:20 UTC, alinnegrea commented on java-grupa8/homework-2/src/main/java/ro/siit/java8/main.java
> +        for (int i = 0; i < 10; i++) {
I tried to use a for for the Bubble Sort. You are right the method was not a Bubble sort.. i read the extra conditions and modified the code.

2017-11-16 06:44 UTC, merged